baseURL: "http://www.example.com"
title: "NumEconCPH"
theme: "NumEconCopenhagenTheme"

menu:
  menu1:
    - name: "Exercises"
      url: "/exercises/"
      weight: 10
    - name: "Lectures"
      url: "/lectures/"
      weight: 20
    - name: "Guides"
      url: "/guides/"
  menu2:
    - name: "Course plan"
      url: "/course-plan/"
  menu3:
    - name: "GitHub"
      url: "https://github.com/NumEconCopenhagen"
      weight: 10
    - name: "NumEcon"
      url: "https://github.com/NumEconCopenhagen/NumEcon"
      weight: 20


ignorefiles: []
