baseURL: "http://www.example.com"
title: "NumEconCPH"
theme: "NumEconCopenhagenTheme"

menu:
  menu1:
    - name: "Exercises"
      url: "/exercises/"
      weight: 10
    - name: "Lectures"
      url: "/lectures/"
      weight: 20
  menu2:
    - name: "Course Plan"
      url: "/course-plan-table/"
  menu3:
    - name: "Github"
      url: "https://github.com/NumEconCopenhagen"
      weight: 10
    - name: "NumEcon"
      url: "https://github.com/NumEconCopenhagen/NumEcon"
      weight: 20


ignorefiles: []